# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 80
    context-path: /

# mysql
spring:
    # 环境 dev|test|pro
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
#    http:
#        multipart:
#        max-file-size: 100MB
#        max-request-size: 100MB
#        enabled: true
    # 指定静态资源的路径
    mvc:
          static-path-pattern: /static/**
    resources:
        static-locations: classpath:/static/**,classpath:/templates/**

    freemarker:
             cache: false
             content-type: text/html
             enabled: true
             charset: utf-8
             request-context-attribute: request
             check-template-location: true
             expose-spring-macro-helpers: true
             expose-session-attributes: true
             expose-request-attributes: true
# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml


